name: Bug Report
description: Create a bug report to help us improve
title: "[Bug] "
body:
  - type: textarea
    id: desc
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is and how to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please add screenshots to help explain your problem
